/**
 * @author Ollie Beenham
 */

import "@/styles/default.css";
import type { Metadata } from "next";
import { PublicEnvScript } from "next-runtime-env";

/**
 * Metadata for the root layout.
 */
export const metadata: Metadata = {
	title: {
		template: "%s | Dashboard App",
		default: "Home | Dashboard App",
	},
	icons: {
		icon: `/api/public/dashboard-logo`,
	},
	description: "Generated by create next app",
};

/**
 * Root layout for the application.
 *
 * @param {React.ReactNode} children Child elements
 * @returns Document layout
 */
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<PublicEnvScript />
			</head>
			<body className={"antialiased"}>
				<div className="w-full h-dvh bg-gray-800 text-white">{children}</div>
			</body>
		</html>
	);
}
