# Volumes
volumes:
    dashboard-data:

services:
    dashboard:
        build:
            context: ../
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - dashboard-data:/app/data
        environment:
            - AUTH_MICROSOFT_ENTRA_ID_ID
            - AUTH_MICROSOFT_ENTRA_ID_ISSUER
            - AUTH_MICROSOFT_ENTRA_ID_SECRET
            - AUTH_SECRET
            - AUTH_URL
    mongo:
        image: mongo:latest
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
