import type { Metadata } from "next";
import "@/styles/default.css";
import { PublicEnvScript } from "next-runtime-env";

export const metadata: Metadata = {
	title: {
		template: "%s | Dashboard App",
		default: "Home | Dashboard App",
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<PublicEnvScript />
			</head>
			<body className={"antialiased"}>{children}</body>
		</html>
	);
}
