import type { Metadata } from "next";
import "@/styles/default.css";

export const metadata: Metadata = {
	title: {
		template: "%s | Dashboard App",
		default: "Home | Dashboard App",
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={"antialiased"}>{children}</body>
		</html>
	);
}
