/**
 * @author Ollie Beenham
 */

import "@/styles/default.css";
import { Metadata } from "next";
import { PublicEnvScript } from "next-runtime-env";

/**
 * Metadata for the root layout.
 */
export const metadata: Metadata = {
	title: {
		template: "%s | Dashboard App",
		default: "Auth | Dashboard App",
	},
	icons: {
		icon: `/api/public/dashboard-logo`,
	},
	description: "Generated by create next app",
};

/**
 * Root layout for the authentication pages of the application.
 *
 * @param {React.ReactNode} children Child elements
 * @returns Document layout
 */
export default function AuthLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<PublicEnvScript />
			</head>
			<body id="auth-body" className="antialiased text-white max-h-dvh">
				<div className="w-full h-dvh flex items-center justify-center flex-col bg-black/30">
					{children}
				</div>
			</body>
		</html>
	);
}
