/**
 * @author Ollie Beenham
 */

import { getTitle } from "@/lib/db/local/queries";
import { Metadata } from "next";
import LoginForm from "./LoginForm";
import IdentityProviders from "./IdentityProviders";

/**
 * Metadata for the login page.
 */
export const metadata: Metadata = {
	title: "Login",
	description: "Generated by create next app",
};

/**
 * Login page
 *
 * @returns {Promise<JSX.Element>} Login page
 */
export default async function Login({
	searchParams,
}: {
	searchParams?: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
	// Get the redirect URL from the query string
	const redirectURL = ((await searchParams)?.redirectTo as string) || "/";

	// Get the app name
	const appName = (await getTitle()).title;

	// Redirect to the login page
	return (
		<div className="flex flex-col items-center justify-center gap-5 p-10 bg-white text-black w-1/3 rounded-xl">
			<img src="/api/public/dashboard-logo" alt="Logo" className="w-24" />

			<h1 className="text-md text-center font-medium">{appName}</h1>

			{/* Login Form */}
			<LoginForm redirect={redirectURL} />

			{/* IDP Options */}
			<IdentityProviders redirect={redirectURL} />
		</div>
	);
}
