---
# Kubernetes Service Definition

apiVersion: v1
kind: Service
metadata:
    name: portfolio-dashboard
    namespace: portfolio-dashboard
spec:
    type: NodePort
    selector:
        app: portfolio-dashboard
    ports:
        - port: 3000
          nodePort: 32181
          name: http
