name: CI - Release

on:
    push:
        branches: [production]

jobs:
    get_project_version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 23
              uses: actions/setup-node@v3
              with:
                  node-version: 23
                  cache: "npm"
            - name: Get project version
              run: |
                  npm install
                  export VERSION=$(node -p "require('./package.json').version")
                  echo "VERSION=$VERSION" >> variables.env
            - uses: actions/upload-artifact@v3
              with:
                  name: variables.env
                  path: variables.env

    create_release_old:
        runs-on: ubuntu-latest
        needs: [get_project_version]
        steps:
            - uses: actions/checkout@v3
            - name: Download release-cli action
              uses: gr2m/release-action@v1.4.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Release
              run: |
                  echo "Creating release $VERSION"
            - name: Create release on GitHub
              uses: gr2m/release-action@v1.4.0
              env:
                  VERSION: ${{ needs.get_project_version.outputs.VERSION }}
              with:
                  tag_name: ${{ needs.get_project_version.outputs.VERSION }}
                  description: |

                  ref: ${{ github.sha }}
                  assets: |
                      {
                        "links": [
                          { "name": "Docker Image", "url": "https://hub.docker.com/r/beenhamo/portfolio-dashboard" }
                        ]
                      }
    create_release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Create Release
              id: create_release
              uses: comnoco/create-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ needs.get_project_version.outputs.VERSION }}
                  release_name: Version ${{ needs.get_project_version.outputs.VERSION }}
                  body: |
                      This is the release for version ${{ needs.get_project_version.outputs.VERSION }}.

                      [Docker Image](https://hub.docker.com/r/beenhamo/portfolio-dashboard)
                  draft: false
                  prerelease: false
